// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using training_management_internship.Models;

#nullable disable

namespace training_management_internship.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250527152338_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("training_management_internship.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HocHamHocVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiCongTac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoCanCuoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ThuocBenhVien")
                        .HasColumnType("bit");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("training_management_internship.Models.ChiTietLop", b =>
                {
                    b.Property<int>("ChiTietLopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietLopId"));

                    b.Property<int?>("GiangVienId")
                        .HasColumnType("int");

                    b.Property<int>("LopId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayHoc")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("ThoiGianBatDau")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("ThoiGianKetThuc")
                        .HasColumnType("time");

                    b.HasKey("ChiTietLopId");

                    b.HasIndex("GiangVienId");

                    b.HasIndex("LopId");

                    b.ToTable("ChiTietLops");
                });

            modelBuilder.Entity("training_management_internship.Models.ChuongTrinhDaoTao", b =>
                {
                    b.Property<int>("ChuongTrinhDaoTaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChuongTrinhDaoTaoId"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChuongTrinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChuongTrinhDaoTaoId");

                    b.ToTable("ChuongTrinhDaoTaos");
                });

            modelBuilder.Entity("training_management_internship.Models.DangKyKhoaHoc", b =>
                {
                    b.Property<int>("DangKyKhoaHocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DangKyKhoaHocId"));

                    b.Property<int>("HocVienId")
                        .HasColumnType("int");

                    b.Property<int>("KhoaHocId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.HasKey("DangKyKhoaHocId");

                    b.HasIndex("HocVienId");

                    b.HasIndex("KhoaHocId");

                    b.ToTable("DangKyKhoaHocs");
                });

            modelBuilder.Entity("training_management_internship.Models.DanhGia", b =>
                {
                    b.Property<int>("DanhGiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DanhGiaId"));

                    b.Property<int>("DangKyKhoaHocId")
                        .HasColumnType("int");

                    b.Property<string>("LoaiDanhGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DanhGiaId");

                    b.HasIndex("DangKyKhoaHocId");

                    b.ToTable("DanhGias");
                });

            modelBuilder.Entity("training_management_internship.Models.DanhSachHocVien", b =>
                {
                    b.Property<int>("DanhSachHocVienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DanhSachHocVienId"));

                    b.Property<int>("HocVienId")
                        .HasColumnType("int");

                    b.Property<int>("LopId")
                        .HasColumnType("int");

                    b.HasKey("DanhSachHocVienId");

                    b.HasIndex("HocVienId");

                    b.HasIndex("LopId");

                    b.ToTable("DanhSachHocViens");
                });

            modelBuilder.Entity("training_management_internship.Models.DiemDanh", b =>
                {
                    b.Property<int>("DiemDanhId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiemDanhId"));

                    b.Property<TimeSpan>("CheckIn")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("CheckOut")
                        .HasColumnType("time");

                    b.Property<int>("ChiTietLopId")
                        .HasColumnType("int");

                    b.Property<int>("HocVienId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCheck")
                        .HasColumnType("datetime2");

                    b.HasKey("DiemDanhId");

                    b.HasIndex("ChiTietLopId");

                    b.HasIndex("HocVienId");

                    b.ToTable("DiemDanhs");
                });

            modelBuilder.Entity("training_management_internship.Models.GiangVien", b =>
                {
                    b.Property<int>("GiangVienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GiangVienId"));

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("GiangVienId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("GiangViens");
                });

            modelBuilder.Entity("training_management_internship.Models.HocVien", b =>
                {
                    b.Property<int>("HocVienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HocVienId"));

                    b.Property<int>("TongKhoaHoc")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("HocVienId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("HocViens");
                });

            modelBuilder.Entity("training_management_internship.Models.KhoaHoc", b =>
                {
                    b.Property<int>("KhoaHocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KhoaHocId"));

                    b.Property<int>("ChuongTrinhDaoTaoId")
                        .HasColumnType("int");

                    b.Property<int?>("GiangVienId")
                        .HasColumnType("int");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KhoaHocId");

                    b.HasIndex("ChuongTrinhDaoTaoId");

                    b.HasIndex("GiangVienId");

                    b.ToTable("KhoaHocs");
                });

            modelBuilder.Entity("training_management_internship.Models.LoaiLop", b =>
                {
                    b.Property<int>("LoaiLopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoaiLopId"));

                    b.Property<string>("TenLoaiLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoaiLopId");

                    b.ToTable("LoaiLops");
                });

            modelBuilder.Entity("training_management_internship.Models.Lop", b =>
                {
                    b.Property<int>("LopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LopId"));

                    b.Property<bool>("CoDanhSachHocVien")
                        .HasColumnType("bit");

                    b.Property<int>("KhoaHocId")
                        .HasColumnType("int");

                    b.Property<int>("LoaiLopId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDauDuKien")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThucDuKien")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoGio")
                        .HasColumnType("int");

                    b.Property<int>("SoGioQuyDoi")
                        .HasColumnType("int");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LopId");

                    b.HasIndex("KhoaHocId");

                    b.HasIndex("LoaiLopId");

                    b.ToTable("Lops");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("training_management_internship.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("training_management_internship.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("training_management_internship.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("training_management_internship.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("training_management_internship.Models.ChiTietLop", b =>
                {
                    b.HasOne("training_management_internship.Models.GiangVien", "GiangVien")
                        .WithMany()
                        .HasForeignKey("GiangVienId");

                    b.HasOne("training_management_internship.Models.Lop", "Lop")
                        .WithMany("ChiTietLops")
                        .HasForeignKey("LopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("Lop");
                });

            modelBuilder.Entity("training_management_internship.Models.DangKyKhoaHoc", b =>
                {
                    b.HasOne("training_management_internship.Models.HocVien", "HocVien")
                        .WithMany("DangKyKhoaHocs")
                        .HasForeignKey("HocVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("training_management_internship.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("DangKyKhoaHocs")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocVien");

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("training_management_internship.Models.DanhGia", b =>
                {
                    b.HasOne("training_management_internship.Models.DangKyKhoaHoc", "DangKyKhoaHoc")
                        .WithMany("DanhGias")
                        .HasForeignKey("DangKyKhoaHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DangKyKhoaHoc");
                });

            modelBuilder.Entity("training_management_internship.Models.DanhSachHocVien", b =>
                {
                    b.HasOne("training_management_internship.Models.HocVien", "HocVien")
                        .WithMany()
                        .HasForeignKey("HocVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("training_management_internship.Models.Lop", "Lop")
                        .WithMany("DanhSachHocViens")
                        .HasForeignKey("LopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocVien");

                    b.Navigation("Lop");
                });

            modelBuilder.Entity("training_management_internship.Models.DiemDanh", b =>
                {
                    b.HasOne("training_management_internship.Models.ChiTietLop", "ChiTietLop")
                        .WithMany("DiemDanhs")
                        .HasForeignKey("ChiTietLopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("training_management_internship.Models.HocVien", "HocVien")
                        .WithMany()
                        .HasForeignKey("HocVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietLop");

                    b.Navigation("HocVien");
                });

            modelBuilder.Entity("training_management_internship.Models.GiangVien", b =>
                {
                    b.HasOne("training_management_internship.Models.ApplicationUser", "User")
                        .WithOne("GiangVien")
                        .HasForeignKey("training_management_internship.Models.GiangVien", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("training_management_internship.Models.HocVien", b =>
                {
                    b.HasOne("training_management_internship.Models.ApplicationUser", "User")
                        .WithOne("HocVien")
                        .HasForeignKey("training_management_internship.Models.HocVien", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("training_management_internship.Models.KhoaHoc", b =>
                {
                    b.HasOne("training_management_internship.Models.ChuongTrinhDaoTao", "ChuongTrinhDaoTao")
                        .WithMany("KhoaHocs")
                        .HasForeignKey("ChuongTrinhDaoTaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("training_management_internship.Models.GiangVien", null)
                        .WithMany("KhoaHocs")
                        .HasForeignKey("GiangVienId");

                    b.Navigation("ChuongTrinhDaoTao");
                });

            modelBuilder.Entity("training_management_internship.Models.Lop", b =>
                {
                    b.HasOne("training_management_internship.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("Lops")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("training_management_internship.Models.LoaiLop", "LoaiLop")
                        .WithMany("Lops")
                        .HasForeignKey("LoaiLopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoaHoc");

                    b.Navigation("LoaiLop");
                });

            modelBuilder.Entity("training_management_internship.Models.ApplicationUser", b =>
                {
                    b.Navigation("GiangVien");

                    b.Navigation("HocVien");
                });

            modelBuilder.Entity("training_management_internship.Models.ChiTietLop", b =>
                {
                    b.Navigation("DiemDanhs");
                });

            modelBuilder.Entity("training_management_internship.Models.ChuongTrinhDaoTao", b =>
                {
                    b.Navigation("KhoaHocs");
                });

            modelBuilder.Entity("training_management_internship.Models.DangKyKhoaHoc", b =>
                {
                    b.Navigation("DanhGias");
                });

            modelBuilder.Entity("training_management_internship.Models.GiangVien", b =>
                {
                    b.Navigation("KhoaHocs");
                });

            modelBuilder.Entity("training_management_internship.Models.HocVien", b =>
                {
                    b.Navigation("DangKyKhoaHocs");
                });

            modelBuilder.Entity("training_management_internship.Models.KhoaHoc", b =>
                {
                    b.Navigation("DangKyKhoaHocs");

                    b.Navigation("Lops");
                });

            modelBuilder.Entity("training_management_internship.Models.LoaiLop", b =>
                {
                    b.Navigation("Lops");
                });

            modelBuilder.Entity("training_management_internship.Models.Lop", b =>
                {
                    b.Navigation("ChiTietLops");

                    b.Navigation("DanhSachHocViens");
                });
#pragma warning restore 612, 618
        }
    }
}
